/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/comparables/{comparable_id}/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Override Route */
        post: operations["create_override_route_api_v1_comparables__comparable_id__overrides_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me Route */
        get: operations["get_me_route_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Opportunities Route */
        get: operations["list_opportunities_route_api_v1_opportunities_get"];
        put?: never;
        /** Create Opportunity Route */
        post: operations["create_opportunity_route_api_v1_opportunities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Opportunity Route */
        get: operations["get_opportunity_route_api_v1_opportunities__opportunity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Opportunity Route */
        patch: operations["patch_opportunity_route_api_v1_opportunities__opportunity_id__patch"];
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/comparables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Comparables Route */
        get: operations["list_comparables_route_api_v1_opportunities__opportunity_id__comparables_get"];
        put?: never;
        /** Create Comparable Route */
        post: operations["create_comparable_route_api_v1_opportunities__opportunity_id__comparables_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Opportunity Events Route */
        get: operations["list_opportunity_events_route_api_v1_opportunities__opportunity_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/price-inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Price Input Route */
        post: operations["add_price_input_route_api_v1_opportunities__opportunity_id__price_inputs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/reference-confirmations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Reference Route */
        post: operations["confirm_reference_route_api_v1_opportunities__opportunity_id__reference_confirmations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/seller-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Seller Profile Route */
        patch: operations["patch_seller_profile_route_api_v1_opportunities__opportunity_id__seller_profile_patch"];
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/watch-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Watch Profile Route */
        patch: operations["patch_watch_profile_route_api_v1_opportunities__opportunity_id__watch_profile_patch"];
        trace?: never;
    };
    "/api/v1/platforms/{code}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Platform Rules Route */
        get: operations["get_platform_rules_route_api_v1_platforms__code__rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEventPage */
        AuditEventPage: {
            /** Items */
            items: components["schemas"]["AuditEventResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** AuditEventResponse */
        AuditEventResponse: {
            /** Action */
            action: string;
            /** Actor User Id */
            actor_user_id: string | null;
            /** After Data */
            after_data: {
                [key: string]: unknown;
            } | null;
            /** Before Data */
            before_data: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Reason */
            reason: string;
            /**
             * Resource Id
             * Format: uuid
             */
            resource_id: string;
            /** Resource Type */
            resource_type: string;
        };
        /**
         * ComparableCreate
         * @description Comparable saisi manuellement.
         *
         *     `price_kind` décrit la nature économique du prix, `source_reliability` la
         *     qualité de la preuve : les deux sont obligatoires et ne se substituent pas
         *     l'un à l'autre (calculation-spec.md § 2).
         */
        ComparableCreate: {
            /** Amount */
            amount: number | string;
            /** Box */
            box?: boolean | null;
            /** Buyer Fixed Fee Eur */
            buyer_fixed_fee_eur?: number | string | null;
            /** Buyer Variable Fee Eur */
            buyer_variable_fee_eur?: number | string | null;
            /** Compulsory Shipping Eur */
            compulsory_shipping_eur?: number | string | null;
            /** Cosmetic Condition */
            cosmetic_condition?: string | null;
            /** Currency */
            currency: string;
            /** Ended At */
            ended_at?: string | null;
            /** Listed At */
            listed_at?: string | null;
            /**
             * Market Status
             * @enum {string}
             */
            market_status: "active" | "sold" | "removed" | "ended" | "unknown";
            /** Mechanical Condition */
            mechanical_condition?: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Papers */
            papers?: boolean | null;
            /**
             * Price Kind
             * @enum {string}
             */
            price_kind: "asking" | "offer" | "accepted_offer" | "current_bid" | "hammer" | "realized" | "external_estimate" | "kairos_estimate";
            /** Seller Fingerprint */
            seller_fingerprint?: string | null;
            /** Source External Id */
            source_external_id?: string | null;
            /** Source Name */
            source_name: string;
            /**
             * Source Reliability
             * @enum {string}
             */
            source_reliability: "a" | "b" | "c" | "d" | "e";
        };
        /** ComparablePage */
        ComparablePage: {
            /** Items */
            items: components["schemas"]["ComparableResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ComparableResponse */
        ComparableResponse: {
            /** Amount Eur */
            amount_eur: string;
            /** Amount Source */
            amount_source: string;
            /** Buyer Total Price Eur */
            buyer_total_price_eur: string;
            /** Completeness Data */
            completeness_data: {
                [key: string]: unknown;
            };
            /** Condition Data */
            condition_data: {
                [key: string]: unknown;
            };
            /** Currency */
            currency: string;
            /** Ended At */
            ended_at: string | null;
            /** Excluded */
            excluded: boolean;
            /** Exclusion Reason */
            exclusion_reason: string | null;
            /**
             * Fx Rate At
             * Format: date-time
             */
            fx_rate_at: string;
            /** Fx Source */
            fx_source: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Listed At */
            listed_at: string | null;
            /** Market Status */
            market_status: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Price Kind */
            price_kind: string;
            /** Rate To Eur */
            rate_to_eur: string;
            /** Source Name */
            source_name: string;
            /** Source Reliability */
            source_reliability: string;
        };
        /** CreateOpportunityRequest */
        CreateOpportunityRequest: {
            /**
             * Portfolio Id
             * Format: uuid
             */
            portfolio_id: string;
            /**
             * @default {
             *       "missing_reason": "asking_price_not_provided"
             *     }
             */
            price: components["schemas"]["PriceCreate"];
            /** @default {} */
            seller: components["schemas"]["SellerCreate"];
            source: components["schemas"]["SourceCreate"];
            watch: components["schemas"]["WatchCreate"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OpportunityPage */
        OpportunityPage: {
            /** Items */
            items: components["schemas"]["OpportunityResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** OpportunityPatchRequest */
        OpportunityPatchRequest: {
            /** Reason */
            reason: string;
            /** Strategy Id */
            strategy_id?: string | null;
        };
        /** OpportunityResponse */
        OpportunityResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Latest Analysis */
            latest_analysis?: null;
            latest_price: components["schemas"]["PriceResponse"] | null;
            /** Manual Identifier */
            manual_identifier: string | null;
            /**
             * Portfolio Id
             * Format: uuid
             */
            portfolio_id: string;
            seller: components["schemas"]["SellerProfileResponse"] | null;
            /** Source Mode */
            source_mode: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
            watch: components["schemas"]["WatchProfileResponse"];
        };
        /**
         * OverrideCreate
         * @description Correction, exclusion ou réintégration d'un comparable.
         *
         *     Une exclusion exige son propre motif en plus du motif d'audit : le premier
         *     documente la décision métier, le second la trace (schéma `comparable_overrides`).
         */
        OverrideCreate: {
            /** Corrected Data */
            corrected_data?: {
                [key: string]: unknown;
            };
            /** Excluded */
            excluded: boolean;
            /** Exclusion Reason */
            exclusion_reason?: string | null;
            /** Reason */
            reason: string;
        };
        /** OverrideResponse */
        OverrideResponse: {
            /**
             * Comparable Id
             * Format: uuid
             */
            comparable_id: string;
            /** Corrected Data */
            corrected_data: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Excluded */
            excluded: boolean;
            /** Exclusion Reason */
            exclusion_reason: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Previous Override Id */
            previous_override_id: string | null;
            /** Reason */
            reason: string;
        };
        /** PriceCreate */
        PriceCreate: {
            /** Amount */
            amount?: number | string | null;
            /** Currency */
            currency?: string | null;
            /** Missing Reason */
            missing_reason?: string | null;
        };
        /** PriceInputCreate */
        PriceInputCreate: {
            /** Amount */
            amount?: number | string | null;
            /** Currency */
            currency?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "asking" | "offer" | "accepted_offer" | "current_bid" | "hammer";
            /** Missing Reason */
            missing_reason?: string | null;
        };
        /** PriceResponse */
        PriceResponse: {
            /** Amount */
            amount: string | null;
            /** Amount Eur */
            amount_eur: string | null;
            /** Currency */
            currency: string | null;
            /** Missing Reason */
            missing_reason: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** ReferenceConfirmationRequest */
        ReferenceConfirmationRequest: {
            /** Reason */
            reason: string;
            /** Reference Id */
            reference_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "suggested" | "confirmed" | "corrected" | "unknown";
        };
        /** SellerCreate */
        SellerCreate: {
            /** Country Code */
            country_code?: string | null;
            /** Seller Type */
            seller_type?: string | null;
        };
        /** SellerProfilePatchRequest */
        SellerProfilePatchRequest: {
            /** Country Code */
            country_code?: string | null;
            /** Reason */
            reason: string;
            /** Seller Type */
            seller_type?: string | null;
        };
        /** SellerProfileResponse */
        SellerProfileResponse: {
            /** Country Code */
            country_code: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Seller Type */
            seller_type: string | null;
        };
        /** SourceCreate */
        SourceCreate: {
            /** Manual Identifier */
            manual_identifier?: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "manual" | "url";
            /** Url */
            url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchCreate */
        WatchCreate: {
            /** Box */
            box?: boolean | null;
            /** Brand */
            brand: string;
            /** Cosmetic Condition */
            cosmetic_condition?: string | null;
            /** Mechanical Condition */
            mechanical_condition?: string | null;
            /** Originality */
            originality?: string | null;
            /** Papers */
            papers?: boolean | null;
            /** Reference */
            reference: string;
            /**
             * Reference Status
             * @default unconfirmed
             * @enum {string}
             */
            reference_status: "unconfirmed" | "unknown";
        };
        /** WatchProfilePatchRequest */
        WatchProfilePatchRequest: {
            /** Box */
            box?: boolean | null;
            /** Cosmetic Condition */
            cosmetic_condition?: string | null;
            /** Mechanical Condition */
            mechanical_condition?: string | null;
            /** Originality */
            originality?: string | null;
            /** Papers */
            papers?: boolean | null;
            /** Reason */
            reason: string;
        };
        /** WatchProfileResponse */
        WatchProfileResponse: {
            /** Brand */
            brand: string | null;
            /** Completeness Data */
            completeness_data: {
                [key: string]: unknown;
            };
            /** Condition Data */
            condition_data: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Identification Confidence */
            identification_confidence: string | null;
            /** Reference */
            reference: string | null;
            /** Reference Id */
            reference_id: string | null;
            /** Reference Status */
            reference_status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_override_route_api_v1_comparables__comparable_id__overrides_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comparable_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_me_route_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_opportunities_route_api_v1_opportunities_get: {
        parameters: {
            query?: {
                status?: string | null;
                brand?: string | null;
                reference?: string | null;
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_opportunity_route_api_v1_opportunities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOpportunityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_opportunity_route_api_v1_opportunities__opportunity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_opportunity_route_api_v1_opportunities__opportunity_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_comparables_route_api_v1_opportunities__opportunity_id__comparables_get: {
        parameters: {
            query?: {
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparablePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_comparable_route_api_v1_opportunities__opportunity_id__comparables_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparableCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_opportunity_events_route_api_v1_opportunities__opportunity_id__events_get: {
        parameters: {
            query?: {
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_price_input_route_api_v1_opportunities__opportunity_id__price_inputs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceInputCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_reference_route_api_v1_opportunities__opportunity_id__reference_confirmations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferenceConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_seller_profile_route_api_v1_opportunities__opportunity_id__seller_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SellerProfilePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_watch_profile_route_api_v1_opportunities__opportunity_id__watch_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchProfilePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_platform_rules_route_api_v1_platforms__code__rules_get: {
        parameters: {
            query?: {
                region?: string;
                at?: string | null;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
