/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me Route */
        get: operations["get_me_route_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Opportunities Route */
        get: operations["list_opportunities_route_api_v1_opportunities_get"];
        put?: never;
        /** Create Opportunity Route */
        post: operations["create_opportunity_route_api_v1_opportunities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Opportunity Route */
        get: operations["get_opportunity_route_api_v1_opportunities__opportunity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Opportunity Route */
        patch: operations["patch_opportunity_route_api_v1_opportunities__opportunity_id__patch"];
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Opportunity Events Route */
        get: operations["list_opportunity_events_route_api_v1_opportunities__opportunity_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/price-inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Price Input Route */
        post: operations["add_price_input_route_api_v1_opportunities__opportunity_id__price_inputs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/reference-confirmations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Reference Route */
        post: operations["confirm_reference_route_api_v1_opportunities__opportunity_id__reference_confirmations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/seller-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Seller Profile Route */
        patch: operations["patch_seller_profile_route_api_v1_opportunities__opportunity_id__seller_profile_patch"];
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/watch-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Watch Profile Route */
        patch: operations["patch_watch_profile_route_api_v1_opportunities__opportunity_id__watch_profile_patch"];
        trace?: never;
    };
    "/api/v1/platforms/{code}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Platform Rules Route */
        get: operations["get_platform_rules_route_api_v1_platforms__code__rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEventPage */
        AuditEventPage: {
            /** Items */
            items: components["schemas"]["AuditEventResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** AuditEventResponse */
        AuditEventResponse: {
            /** Action */
            action: string;
            /** Actor User Id */
            actor_user_id: string | null;
            /** After Data */
            after_data: {
                [key: string]: unknown;
            } | null;
            /** Before Data */
            before_data: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Reason */
            reason: string;
            /**
             * Resource Id
             * Format: uuid
             */
            resource_id: string;
            /** Resource Type */
            resource_type: string;
        };
        /** CreateOpportunityRequest */
        CreateOpportunityRequest: {
            /**
             * Portfolio Id
             * Format: uuid
             */
            portfolio_id: string;
            /**
             * @default {
             *       "missing_reason": "asking_price_not_provided"
             *     }
             */
            price: components["schemas"]["PriceCreate"];
            /** @default {} */
            seller: components["schemas"]["SellerCreate"];
            source: components["schemas"]["SourceCreate"];
            watch: components["schemas"]["WatchCreate"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OpportunityPage */
        OpportunityPage: {
            /** Items */
            items: components["schemas"]["OpportunityResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** OpportunityPatchRequest */
        OpportunityPatchRequest: {
            /** Reason */
            reason: string;
            /** Strategy Id */
            strategy_id?: string | null;
        };
        /** OpportunityResponse */
        OpportunityResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Latest Analysis */
            latest_analysis?: null;
            latest_price: components["schemas"]["PriceResponse"] | null;
            /** Manual Identifier */
            manual_identifier: string | null;
            /**
             * Portfolio Id
             * Format: uuid
             */
            portfolio_id: string;
            seller: components["schemas"]["SellerProfileResponse"] | null;
            /** Source Mode */
            source_mode: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
            watch: components["schemas"]["WatchProfileResponse"];
        };
        /** PriceCreate */
        PriceCreate: {
            /** Amount */
            amount?: number | string | null;
            /** Currency */
            currency?: string | null;
            /** Missing Reason */
            missing_reason?: string | null;
        };
        /** PriceInputCreate */
        PriceInputCreate: {
            /** Amount */
            amount?: number | string | null;
            /** Currency */
            currency?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "asking" | "offer" | "accepted_offer" | "current_bid" | "hammer";
            /** Missing Reason */
            missing_reason?: string | null;
        };
        /** PriceResponse */
        PriceResponse: {
            /** Amount */
            amount: string | null;
            /** Amount Eur */
            amount_eur: string | null;
            /** Currency */
            currency: string | null;
            /** Missing Reason */
            missing_reason: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** ReferenceConfirmationRequest */
        ReferenceConfirmationRequest: {
            /** Reason */
            reason: string;
            /** Reference Id */
            reference_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "suggested" | "confirmed" | "corrected" | "unknown";
        };
        /** SellerCreate */
        SellerCreate: {
            /** Country Code */
            country_code?: string | null;
            /** Seller Type */
            seller_type?: string | null;
        };
        /** SellerProfilePatchRequest */
        SellerProfilePatchRequest: {
            /** Country Code */
            country_code?: string | null;
            /** Reason */
            reason: string;
            /** Seller Type */
            seller_type?: string | null;
        };
        /** SellerProfileResponse */
        SellerProfileResponse: {
            /** Country Code */
            country_code: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Seller Type */
            seller_type: string | null;
        };
        /** SourceCreate */
        SourceCreate: {
            /** Manual Identifier */
            manual_identifier?: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "manual" | "url";
            /** Url */
            url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchCreate */
        WatchCreate: {
            /** Box */
            box?: boolean | null;
            /** Brand */
            brand: string;
            /** Cosmetic Condition */
            cosmetic_condition?: string | null;
            /** Mechanical Condition */
            mechanical_condition?: string | null;
            /** Originality */
            originality?: string | null;
            /** Papers */
            papers?: boolean | null;
            /** Reference */
            reference: string;
            /**
             * Reference Status
             * @default unconfirmed
             * @enum {string}
             */
            reference_status: "unconfirmed" | "unknown";
        };
        /** WatchProfilePatchRequest */
        WatchProfilePatchRequest: {
            /** Box */
            box?: boolean | null;
            /** Cosmetic Condition */
            cosmetic_condition?: string | null;
            /** Mechanical Condition */
            mechanical_condition?: string | null;
            /** Originality */
            originality?: string | null;
            /** Papers */
            papers?: boolean | null;
            /** Reason */
            reason: string;
        };
        /** WatchProfileResponse */
        WatchProfileResponse: {
            /** Brand */
            brand: string | null;
            /** Completeness Data */
            completeness_data: {
                [key: string]: unknown;
            };
            /** Condition Data */
            condition_data: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Identification Confidence */
            identification_confidence: string | null;
            /** Reference */
            reference: string | null;
            /** Reference Id */
            reference_id: string | null;
            /** Reference Status */
            reference_status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_me_route_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_opportunities_route_api_v1_opportunities_get: {
        parameters: {
            query?: {
                status?: string | null;
                brand?: string | null;
                reference?: string | null;
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_opportunity_route_api_v1_opportunities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOpportunityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_opportunity_route_api_v1_opportunities__opportunity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_opportunity_route_api_v1_opportunities__opportunity_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_opportunity_events_route_api_v1_opportunities__opportunity_id__events_get: {
        parameters: {
            query?: {
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_price_input_route_api_v1_opportunities__opportunity_id__price_inputs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceInputCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_reference_route_api_v1_opportunities__opportunity_id__reference_confirmations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferenceConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_seller_profile_route_api_v1_opportunities__opportunity_id__seller_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SellerProfilePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_watch_profile_route_api_v1_opportunities__opportunity_id__watch_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchProfilePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_platform_rules_route_api_v1_platforms__code__rules_get: {
        parameters: {
            query?: {
                region?: string;
                at?: string | null;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
