/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/comparables/{comparable_id}/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Override Route */
        post: operations["create_override_route_api_v1_comparables__comparable_id__overrides_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me Route */
        get: operations["get_me_route_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Opportunities Route */
        get: operations["list_opportunities_route_api_v1_opportunities_get"];
        put?: never;
        /** Create Opportunity Route */
        post: operations["create_opportunity_route_api_v1_opportunities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Opportunity Route */
        get: operations["get_opportunity_route_api_v1_opportunities__opportunity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Opportunity Route */
        patch: operations["patch_opportunity_route_api_v1_opportunities__opportunity_id__patch"];
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Analysis Route
         * @description Recalcule l'analyse. Chaque appel crée une version chaînée à la
         *     précédente : une analyse n'est jamais écrasée (CLAUDE.md règle 4).
         */
        post: operations["create_analysis_route_api_v1_opportunities__opportunity_id__analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/analyses/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Analysis Route */
        get: operations["get_latest_analysis_route_api_v1_opportunities__opportunity_id__analyses_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/comparables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Comparables Route */
        get: operations["list_comparables_route_api_v1_opportunities__opportunity_id__comparables_get"];
        put?: never;
        /** Create Comparable Route */
        post: operations["create_comparable_route_api_v1_opportunities__opportunity_id__comparables_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/comparables/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Comparables Route */
        post: operations["import_comparables_route_api_v1_opportunities__opportunity_id__comparables_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Opportunity Events Route */
        get: operations["list_opportunity_events_route_api_v1_opportunities__opportunity_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/price-inputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Price Input Route */
        post: operations["add_price_input_route_api_v1_opportunities__opportunity_id__price_inputs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/reference-confirmations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Reference Route */
        post: operations["confirm_reference_route_api_v1_opportunities__opportunity_id__reference_confirmations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/seller-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Seller Profile Route */
        patch: operations["patch_seller_profile_route_api_v1_opportunities__opportunity_id__seller_profile_patch"];
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/valuations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Valuation Route
         * @description Recalcule la cote. Chaque appel crée une version : une valorisation
         *     publiée n'est jamais écrasée (CLAUDE.md règle 4).
         */
        post: operations["create_valuation_route_api_v1_opportunities__opportunity_id__valuations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/valuations/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest Valuation Route
         * @description Dernière cote calculée.
         *
         *     Sans elle, l'écran repartirait de zéro à chaque ouverture et prétendrait
         *     qu'aucune cote n'existe alors que l'analyse vient de s'appuyer dessus.
         */
        get: operations["get_latest_valuation_route_api_v1_opportunities__opportunity_id__valuations_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/{opportunity_id}/watch-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Watch Profile Route */
        patch: operations["patch_watch_profile_route_api_v1_opportunities__opportunity_id__watch_profile_patch"];
        trace?: never;
    };
    "/api/v1/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Platforms Route
         * @description Plateformes connues et grille en vigueur pour chacune.
         *
         *     Une plateforme sans grille est signalée comme telle : une opportunité qui
         *     en vient ne peut pas être analysée, faute de pouvoir établir ses coûts.
         */
        get: operations["list_platforms_route_api_v1_platforms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platforms/{code}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Platform Rules Route */
        get: operations["get_platform_rules_route_api_v1_platforms__code__rules_get"];
        put?: never;
        /**
         * Create Platform Rule Route
         * @description Enregistre une grille de frais, en nouvelle version.
         *
         *     La précédente est fermée, jamais réécrite : une analyse produite sous
         *     l'ancienne grille reste rejouable.
         */
        post: operations["create_platform_rule_route_api_v1_platforms__code__rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}/ledger-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Ledger Entry Route
         * @description Ajoute un mouvement de trésorerie.
         *
         *     Le registre est append-only : on ne corrige pas une écriture, on en passe
         *     une autre en sens inverse. C'est ce qui permet à la trésorerie de
         *     s'expliquer ligne à ligne.
         */
        post: operations["create_ledger_entry_route_api_v1_portfolios__portfolio_id__ledger_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio Overview Route */
        get: operations["get_portfolio_overview_route_api_v1_portfolios__portfolio_id__overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisResponse
         * @description Analyse figée et sa trace complète.
         *
         *     Tous les nombres sont des chaînes décimales : un score, un ROI ou un prix
         *     qui transiterait en flottant perdrait la valeur exacte qui a été calculée
         *     et figée (api-contract.md, CLAUDE.md règle 2).
         *
         *     `explanation`, `pillars`, `caps` et `scenario_results` portent les entrées,
         *     règles, versions, exclusions, plafonds et motifs qu'exige la règle 6 :
         *     une recommandation doit pouvoir être rejouée et contestée.
         */
        AnalysisResponse: {
            /**
             * Calculated At
             * Format: date-time
             */
            calculated_at: string;
            /** Caps */
            caps: {
                [key: string]: unknown;
            }[];
            /** Current Price Eur */
            current_price_eur?: string | null;
            /** Evidence Quality Score */
            evidence_quality_score?: string | null;
            /** Expected Days To Sell */
            expected_days_to_sell?: number | null;
            /** Expected Profit Eur */
            expected_profit_eur?: string | null;
            /** Expected Roi */
            expected_roi?: string | null;
            /** Expected Sale Price Eur */
            expected_sale_price_eur?: string | null;
            /** Explanation */
            explanation: {
                [key: string]: unknown;
            };
            /** Gates */
            gates: components["schemas"]["GateResultResponse"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Max Purchase Price Eur */
            max_purchase_price_eur?: string | null;
            /**
             * Opportunity Id
             * Format: uuid
             */
            opportunity_id: string;
            /** Pillars */
            pillars?: {
                [key: string]: unknown;
            } | null;
            /** Portfolio Snapshot */
            portfolio_snapshot?: {
                [key: string]: unknown;
            } | null;
            /** Raw Max Purchase Price Eur */
            raw_max_purchase_price_eur?: string | null;
            /** Recommendation */
            recommendation: string;
            /** Scenario Results */
            scenario_results?: {
                [key: string]: unknown;
            } | null;
            /** Score */
            score?: string | null;
            /** State */
            state: string;
            /** Strategy Snapshot */
            strategy_snapshot?: {
                [key: string]: unknown;
            } | null;
            /** Total Cost Eur */
            total_cost_eur?: string | null;
        };
        /** AuditEventPage */
        AuditEventPage: {
            /** Items */
            items: components["schemas"]["AuditEventResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** AuditEventResponse */
        AuditEventResponse: {
            /** Action */
            action: string;
            /** Actor User Id */
            actor_user_id: string | null;
            /** After Data */
            after_data: {
                [key: string]: unknown;
            } | null;
            /** Before Data */
            before_data: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Reason */
            reason: string;
            /**
             * Resource Id
             * Format: uuid
             */
            resource_id: string;
            /** Resource Type */
            resource_type: string;
        };
        /**
         * ComparableCreate
         * @description Comparable saisi manuellement.
         *
         *     `price_kind` décrit la nature économique du prix, `source_reliability` la
         *     qualité de la preuve : les deux sont obligatoires et ne se substituent pas
         *     l'un à l'autre (calculation-spec.md § 2).
         */
        ComparableCreate: {
            /** Amount */
            amount: number | string;
            /** Box */
            box?: boolean | null;
            /** Buyer Fixed Fee Eur */
            buyer_fixed_fee_eur?: number | string | null;
            /** Buyer Variable Fee Eur */
            buyer_variable_fee_eur?: number | string | null;
            /** Compulsory Shipping Eur */
            compulsory_shipping_eur?: number | string | null;
            /** Cosmetic Condition */
            cosmetic_condition?: string | null;
            /** Currency */
            currency: string;
            /** Ended At */
            ended_at?: string | null;
            /** Listed At */
            listed_at?: string | null;
            /**
             * Market Status
             * @enum {string}
             */
            market_status: "active" | "sold" | "removed" | "ended" | "unknown";
            /** Mechanical Condition */
            mechanical_condition?: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Papers */
            papers?: boolean | null;
            /**
             * Price Kind
             * @enum {string}
             */
            price_kind: "asking" | "offer" | "accepted_offer" | "current_bid" | "hammer" | "realized" | "external_estimate" | "kairos_estimate";
            /** Seller Fingerprint */
            seller_fingerprint?: string | null;
            /** Source External Id */
            source_external_id?: string | null;
            /** Source Name */
            source_name: string;
            /**
             * Source Reliability
             * @enum {string}
             */
            source_reliability: "a" | "b" | "c" | "d" | "e";
        };
        /**
         * ComparableImportRequest
         * @description Contenu CSV lu côté client. Éviter le multipart garde l'API homogène et
         *     testable sans dépendance supplémentaire.
         */
        ComparableImportRequest: {
            /** Content */
            content: string;
        };
        /**
         * ComparableImportResult
         * @description Résultat d'un import CSV.
         *
         *     Les lignes valides sont importées et les lignes en échec rapportées avec
         *     leur numéro : un fichier partiellement erroné ne fait pas perdre le travail
         *     de saisie déjà correct.
         */
        ComparableImportResult: {
            /** Imported */
            imported: number;
            /** Rejected */
            rejected: components["schemas"]["ComparableImportRow"][];
        };
        /** ComparableImportRow */
        ComparableImportRow: {
            /** Error */
            error: string;
            /** Line */
            line: number;
        };
        /** ComparablePage */
        ComparablePage: {
            /** Items */
            items: components["schemas"]["ComparableResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ComparableResponse */
        ComparableResponse: {
            /** Amount Eur */
            amount_eur: string;
            /** Amount Source */
            amount_source: string;
            /** Buyer Total Price Eur */
            buyer_total_price_eur: string;
            /** Completeness Data */
            completeness_data: {
                [key: string]: unknown;
            };
            /** Condition Data */
            condition_data: {
                [key: string]: unknown;
            };
            /** Currency */
            currency: string;
            /** Ended At */
            ended_at: string | null;
            /** Excluded */
            excluded: boolean;
            /** Exclusion Reason */
            exclusion_reason: string | null;
            /**
             * Fx Rate At
             * Format: date-time
             */
            fx_rate_at: string;
            /** Fx Source */
            fx_source: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Listed At */
            listed_at: string | null;
            /** Market Status */
            market_status: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Price Kind */
            price_kind: string;
            /** Rate To Eur */
            rate_to_eur: string;
            /** Source Name */
            source_name: string;
            /** Source Reliability */
            source_reliability: string;
        };
        /** CreateOpportunityRequest */
        CreateOpportunityRequest: {
            /**
             * Portfolio Id
             * Format: uuid
             */
            portfolio_id: string;
            /**
             * @default {
             *       "missing_reason": "asking_price_not_provided"
             *     }
             */
            price: components["schemas"]["PriceCreate"];
            /** @default {} */
            seller: components["schemas"]["SellerCreate"];
            source: components["schemas"]["SourceCreate"];
            watch: components["schemas"]["WatchCreate"];
        };
        /** GateResultResponse */
        GateResultResponse: {
            /** Blocking */
            blocking: boolean;
            /** Code */
            code: string;
            /** Reason Codes */
            reason_codes: string[];
            /** Status */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HoldingResponse */
        HoldingResponse: {
            /** Brand */
            brand?: string | null;
            /** Cost Eur */
            cost_eur: string;
            /**
             * Opportunity Id
             * Format: uuid
             */
            opportunity_id: string;
            /**
             * Purchased At
             * Format: date-time
             */
            purchased_at: string;
            /** Reference */
            reference?: string | null;
        };
        /**
         * LedgerMovementCreate
         * @description Mouvement de trésorerie saisi par l'utilisateur.
         *
         *     Seules les natures sans contrepartie ailleurs sont acceptées. Un paiement
         *     d'achat ou un encaissement de vente a sa ligne dans `purchases` ou
         *     `sales` : le saisir ici ferait diverger le registre des opérations qu'il
         *     reflète.
         *
         *     Le montant est toujours positif — c'est la nature qui porte le sens, comme
         *     dans le registre lui-même.
         */
        LedgerMovementCreate: {
            /** Amount */
            amount: number | string;
            /** Currency */
            currency: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "capital_contribution" | "withdrawal" | "positive_adjustment" | "negative_adjustment";
            /** Notes */
            notes?: string | null;
            /** Occurred At */
            occurred_at?: string | null;
        };
        /**
         * LedgerMovementResponse
         * @description Une écriture du registre, avec la traçabilité de change qu'exige la
         *     règle 3 : devise source, montant EUR, taux, source et horodatage.
         */
        LedgerMovementResponse: {
            /** Amount Eur */
            amount_eur: string;
            /** Amount Source */
            amount_source: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Currency */
            currency: string;
            /**
             * Fx Rate At
             * Format: date-time
             */
            fx_rate_at: string;
            /** Fx Source */
            fx_source: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Notes */
            notes?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Rate To Eur */
            rate_to_eur: string;
        };
        /** OpportunityPage */
        OpportunityPage: {
            /** Items */
            items: components["schemas"]["OpportunityResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** OpportunityPatchRequest */
        OpportunityPatchRequest: {
            /** Reason */
            reason: string;
            /** Strategy Id */
            strategy_id?: string | null;
        };
        /** OpportunityResponse */
        OpportunityResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Latest Analysis */
            latest_analysis?: null;
            latest_price: components["schemas"]["PriceResponse"] | null;
            /** Manual Identifier */
            manual_identifier: string | null;
            /**
             * Portfolio Id
             * Format: uuid
             */
            portfolio_id: string;
            seller: components["schemas"]["SellerProfileResponse"] | null;
            /** Source Mode */
            source_mode: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
            watch: components["schemas"]["WatchProfileResponse"];
        };
        /**
         * OverrideCreate
         * @description Correction, exclusion ou réintégration d'un comparable.
         *
         *     Une exclusion exige son propre motif en plus du motif d'audit : le premier
         *     documente la décision métier, le second la trace (schéma `comparable_overrides`).
         */
        OverrideCreate: {
            /** Corrected Data */
            corrected_data?: {
                [key: string]: unknown;
            };
            /** Excluded */
            excluded: boolean;
            /** Exclusion Reason */
            exclusion_reason?: string | null;
            /** Reason */
            reason: string;
        };
        /** OverrideResponse */
        OverrideResponse: {
            /**
             * Comparable Id
             * Format: uuid
             */
            comparable_id: string;
            /** Corrected Data */
            corrected_data: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Excluded */
            excluded: boolean;
            /** Exclusion Reason */
            exclusion_reason: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Previous Override Id */
            previous_override_id: string | null;
            /** Reason */
            reason: string;
        };
        /** PlatformResponse */
        PlatformResponse: {
            active_rule?: components["schemas"]["PlatformRuleResponse"] | null;
            /** Code */
            code: string;
            /** Has Active Rule */
            has_active_rule: boolean;
            /** Name */
            name: string;
        };
        /**
         * PlatformRuleCreate
         * @description Grille de frais saisie à la main.
         *
         *     Aucun champ n'a de valeur par défaut : inventer une commission fausserait
         *     tous les profits d'un portefeuille sans que rien ne le signale. Tout
         *     laisser vide est accepté — c'est une plateforme sans frais, et c'est un
         *     constat, pas un oubli.
         *
         *     `provenance_url` est obligatoire : une grille qu'on ne peut pas vérifier
         *     ne vaut pas mieux qu'une grille inventée.
         */
        PlatformRuleCreate: {
            /** Buyer Fee Fixed */
            buyer_fee_fixed?: number | string | null;
            /** Buyer Fee Max */
            buyer_fee_max?: number | string | null;
            /** Buyer Fee Min */
            buyer_fee_min?: number | string | null;
            /** Buyer Fee Rate */
            buyer_fee_rate?: number | string | null;
            /**
             * Currency
             * @default EUR
             */
            currency: string;
            /** Provenance Url */
            provenance_url: string;
            /**
             * Region Code
             * @default *
             */
            region_code: string;
            /** Seller Fee Fixed */
            seller_fee_fixed?: number | string | null;
            /** Seller Fee Max */
            seller_fee_max?: number | string | null;
            /** Seller Fee Min */
            seller_fee_min?: number | string | null;
            /** Seller Fee Rate */
            seller_fee_rate?: number | string | null;
        };
        /** PlatformRuleResponse */
        PlatformRuleResponse: {
            /** Access Authorized */
            access_authorized: boolean;
            /** Access Method */
            access_method: string;
            /** Buyer Fee Fixed */
            buyer_fee_fixed?: string | null;
            /** Buyer Fee Max */
            buyer_fee_max?: string | null;
            /** Buyer Fee Min */
            buyer_fee_min?: string | null;
            /** Buyer Fee Rate */
            buyer_fee_rate?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Platform Code */
            platform_code: string;
            /** Provenance Url */
            provenance_url?: string | null;
            /** Region Code */
            region_code: string;
            /** Seller Fee Fixed */
            seller_fee_fixed?: string | null;
            /** Seller Fee Max */
            seller_fee_max?: string | null;
            /** Seller Fee Min */
            seller_fee_min?: string | null;
            /** Seller Fee Rate */
            seller_fee_rate?: string | null;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
            /** Version */
            version: number;
        };
        /**
         * PortfolioOverviewResponse
         * @description Trésorerie, stock et détail.
         *
         *     Le stock est détaillé plutôt que résumé : annoncer un taux
         *     d'immobilisation sans dire quelles montres immobilisent le capital ne dit
         *     pas quoi vendre.
         */
        PortfolioOverviewResponse: {
            /** Available Cash Eur */
            available_cash_eur: string;
            /** Holdings */
            holdings: components["schemas"]["HoldingResponse"][];
            /** Movements */
            movements: components["schemas"]["LedgerMovementResponse"][];
            /**
             * Portfolio Id
             * Format: uuid
             */
            portfolio_id: string;
            /** Stock At Cost Eur */
            stock_at_cost_eur: string;
            /** Total Capital Eur */
            total_capital_eur: string;
        };
        /** PriceCreate */
        PriceCreate: {
            /** Amount */
            amount?: number | string | null;
            /** Currency */
            currency?: string | null;
            /** Missing Reason */
            missing_reason?: string | null;
        };
        /** PriceInputCreate */
        PriceInputCreate: {
            /** Amount */
            amount?: number | string | null;
            /** Currency */
            currency?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "asking" | "offer" | "accepted_offer" | "current_bid" | "hammer";
            /** Missing Reason */
            missing_reason?: string | null;
        };
        /** PriceResponse */
        PriceResponse: {
            /** Amount */
            amount: string | null;
            /** Amount Eur */
            amount_eur: string | null;
            /** Currency */
            currency: string | null;
            /** Missing Reason */
            missing_reason: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** ReferenceConfirmationRequest */
        ReferenceConfirmationRequest: {
            /** Reason */
            reason: string;
            /** Reference Id */
            reference_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "suggested" | "confirmed" | "corrected" | "unknown";
        };
        /**
         * SellerCreate
         * @description Profil du vendeur tel qu'on le constate.
         *
         *     Fiabilité, risque et protections ne sont pas des jugements de valeur :
         *     ce sont des faits que la porte « risque vendeur » et le pilier « qualité
         *     des preuves » consomment tels quels. Les laisser vides est légitime — ils
         *     retombent alors sur « inconnu », qui a sa propre note, jamais sur une
         *     valeur favorable.
         */
        SellerCreate: {
            /** Country Code */
            country_code?: string | null;
            /** Reliability */
            reliability?: string | null;
            /** Risk Level */
            risk_level?: string | null;
            /** Seller Type */
            seller_type?: string | null;
            /** Transaction Protections */
            transaction_protections?: string | null;
        };
        /** SellerProfilePatchRequest */
        SellerProfilePatchRequest: {
            /** Country Code */
            country_code?: string | null;
            /** Reason */
            reason: string;
            /** Reliability */
            reliability?: string | null;
            /** Risk Level */
            risk_level?: string | null;
            /** Seller Type */
            seller_type?: string | null;
            /** Transaction Protections */
            transaction_protections?: string | null;
        };
        /** SellerProfileResponse */
        SellerProfileResponse: {
            /** Country Code */
            country_code: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reliability */
            reliability?: string | null;
            /** Risk Level */
            risk_level?: string | null;
            /** Seller Type */
            seller_type: string | null;
            /** Transaction Protections */
            transaction_protections?: string | null;
        };
        /** SourceCreate */
        SourceCreate: {
            /** Manual Identifier */
            manual_identifier?: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "manual" | "url";
            /** Url */
            url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValuationResponse
         * @description Cote figée et sa trace.
         *
         *     `explanation` porte les entrées, exclusions, plafonds et versions exigés
         *     par la règle 6 : une cote doit pouvoir être rejouée et contestée.
         */
        ValuationResponse: {
            /**
             * Calculated At
             * Format: date-time
             */
            calculated_at: string;
            /** Central Value Eur */
            central_value_eur: string;
            /** Explanation */
            explanation: {
                [key: string]: unknown;
            };
            /** High Value Eur */
            high_value_eur: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Low Value Eur */
            low_value_eur: string;
            /**
             * Opportunity Id
             * Format: uuid
             */
            opportunity_id: string;
            /** Valuation Confidence */
            valuation_confidence: string;
        };
        /** WatchCreate */
        WatchCreate: {
            /** Box */
            box?: boolean | null;
            /** Brand */
            brand: string;
            /** Cosmetic Condition */
            cosmetic_condition?: string | null;
            /** Mechanical Condition */
            mechanical_condition?: string | null;
            /** Originality */
            originality?: string | null;
            /** Papers */
            papers?: boolean | null;
            /** Reference */
            reference: string;
            /**
             * Reference Status
             * @default unconfirmed
             * @enum {string}
             */
            reference_status: "unconfirmed" | "unknown";
        };
        /** WatchProfilePatchRequest */
        WatchProfilePatchRequest: {
            /** Box */
            box?: boolean | null;
            /** Cosmetic Condition */
            cosmetic_condition?: string | null;
            /** Mechanical Condition */
            mechanical_condition?: string | null;
            /** Originality */
            originality?: string | null;
            /** Papers */
            papers?: boolean | null;
            /** Reason */
            reason: string;
        };
        /** WatchProfileResponse */
        WatchProfileResponse: {
            /** Brand */
            brand: string | null;
            /** Completeness Data */
            completeness_data: {
                [key: string]: unknown;
            };
            /** Condition Data */
            condition_data: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Identification Confidence */
            identification_confidence: string | null;
            /** Reference */
            reference: string | null;
            /** Reference Id */
            reference_id: string | null;
            /** Reference Status */
            reference_status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_override_route_api_v1_comparables__comparable_id__overrides_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comparable_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_me_route_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_opportunities_route_api_v1_opportunities_get: {
        parameters: {
            query?: {
                status?: string | null;
                brand?: string | null;
                reference?: string | null;
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_opportunity_route_api_v1_opportunities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOpportunityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_opportunity_route_api_v1_opportunities__opportunity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_opportunity_route_api_v1_opportunities__opportunity_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_route_api_v1_opportunities__opportunity_id__analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_analysis_route_api_v1_opportunities__opportunity_id__analyses_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_comparables_route_api_v1_opportunities__opportunity_id__comparables_get: {
        parameters: {
            query?: {
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparablePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_comparable_route_api_v1_opportunities__opportunity_id__comparables_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparableCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparableResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_comparables_route_api_v1_opportunities__opportunity_id__comparables_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparableImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparableImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_opportunity_events_route_api_v1_opportunities__opportunity_id__events_get: {
        parameters: {
            query?: {
                limit?: number | null;
                cursor?: string | null;
            };
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_price_input_route_api_v1_opportunities__opportunity_id__price_inputs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriceInputCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_reference_route_api_v1_opportunities__opportunity_id__reference_confirmations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferenceConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_seller_profile_route_api_v1_opportunities__opportunity_id__seller_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SellerProfilePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_valuation_route_api_v1_opportunities__opportunity_id__valuations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValuationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_valuation_route_api_v1_opportunities__opportunity_id__valuations_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValuationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_watch_profile_route_api_v1_opportunities__opportunity_id__watch_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchProfilePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_platforms_route_api_v1_platforms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformResponse"][];
                };
            };
        };
    };
    get_platform_rules_route_api_v1_platforms__code__rules_get: {
        parameters: {
            query?: {
                region?: string;
                at?: string | null;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_platform_rule_route_api_v1_platforms__code__rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformRuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ledger_entry_route_api_v1_portfolios__portfolio_id__ledger_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LedgerMovementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerMovementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_overview_route_api_v1_portfolios__portfolio_id__overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
